import { create } from 'zustand';
import { persist } from 'zustand/middleware';
const uiInitialState = {
    zoomLevel: 'week',
    ganttStartDate: '',
    ganttPeriod: '3m',
    showLightningLine: true,
    showWeekend: true,
    showCriticalPath: false,
    showResourceView: true,
    uiFontSize: 13,
    uiRowHeight: 36,
    ganttHeaderLevels: { year: true, month: true, week: true, day: true },
};
export const useTaskStore = create()(persist((set) => ({
    tasks: [],
    needsReload: false,
    filterStatus: '',
    filterAssignee: '',
    filterPriority: '',
    filterSearch: '',
    theme: 'auto',
    ganttBarOpen: true,
    ...uiInitialState,
    setTasks: (tasks) => set({ tasks }),
    setNeedsReload: (needsReload) => set({ needsReload }),
    setFilter: (filter) => set((s) => ({ ...s, ...filter })),
    setZoomLevel: (zoomLevel) => set({ zoomLevel }),
    setGanttRange: (ganttStartDate, ganttPeriod) => set({ ganttStartDate, ganttPeriod }),
    setShowLightningLine: (showLightningLine) => set({ showLightningLine }),
    setShowWeekend: (showWeekend) => set({ showWeekend }),
    setShowCriticalPath: (showCriticalPath) => set({ showCriticalPath }),
    setShowResourceView: (showResourceView) => set({ showResourceView }),
    setUiFontSize: (uiFontSize) => set({ uiFontSize }),
    setUiRowHeight: (uiRowHeight) => set({ uiRowHeight }),
    setGanttHeaderLevels: (levels) => set((s) => ({
        ganttHeaderLevels: { ...s.ganttHeaderLevels, ...levels },
    })),
    setTheme: (theme) => set({ theme }),
    setGanttBarOpen: (ganttBarOpen) => set({ ganttBarOpen }),
    resetUi: () => set(uiInitialState),
}), {
    name: 'treegantt-ui',
    partialize: (s) => ({
        theme: s.theme,
        zoomLevel: s.zoomLevel,
        ganttStartDate: s.ganttStartDate,
        ganttPeriod: s.ganttPeriod,
        showLightningLine: s.showLightningLine,
        showWeekend: s.showWeekend,
        showCriticalPath: s.showCriticalPath,
        showResourceView: s.showResourceView,
        uiFontSize: s.uiFontSize,
        uiRowHeight: s.uiRowHeight,
        ganttHeaderLevels: s.ganttHeaderLevels,
        ganttBarOpen: s.ganttBarOpen,
    }),
}));
